packages:
  - chapters/第[0-9]章 [^/]+/[0-9][0-9]-[^/]+
  - demo/*
  - concept/*
  - docs
  - packages/*
  - "!node_modules"

catalog:
  webpack: ^5.98.0
  webpack-cli: ^6.0.1
  vitepress: ^1.6.3
  # sass
  sass: ^1.86.1
  # postcss
  postcss-color-mod-function: ^4.1.1
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.5
  # utils
  gsap: ^3.13.0

catalogs:
  webpack4:
    webpack: 4.47.0
    webpack-cli: 4.10.0
    html-webpack-plugin: 4.5.2
    clean-webpack-plugin: 4.0.0
  babel7:
    "@babel/cli": ^7.27.0
    "@babel/preset-env": ^7.26.9
    "@babel/core": ^7.26.10
    core-js: ^3.41.0
    babel-loader: ^10.0.0