packages:
  - chapters/**/*
  - playground/*
  - concept/*
  - packages/*
  - "!node_modules"
  - docs

catalog:
  webpack: ^5.98.0
  webpack-cli: ^6.0.1
  vitepress: ^1.6.3
  # sass
  sass: ^1.86.1
  # postcss
  postcss-color-mod-function: ^4.1.1
  postcss-import: ^16.1.0
  postcss-preset-env: ^10.1.5
  # utils
  gsap: ^3.13.0

catalogs:
  webpack4:
    webpack: 4.47.0
    webpack-cli: 4.10.0
    html-webpack-plugin: 4.5.2
    clean-webpack-plugin: 4.0.0
  babel7:
    "@babel/cli": ^7.27.0
    "@babel/core": ^7.26.10
    babel-loader: ^10.0.0
    core-js: ^3.41.0
    "@babel/preset-env": ^7.26.9
    "@babel/runtime": ^7.27.0
    "@babel/runtime-corejs3": ^7.27.0
    # babel 插件
    "@babel/plugin-transform-class-properties": ^7.27.1
    "@babel/plugin-transform-json-modules": ^7.27.1
    "@babel/plugin-transform-private-property-in-object": ^7.27.1
    babel-plugin-transform-remove-console: ^6.9.4